default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: rails_todo_tutorial_user
  password: test
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_todo_tutorial_development
  host: localhost

test:
  <<: *default
  database: rails_todo_tutorial_test
  host: localhost

production:
  <<: *default
  database: rails_todo_tutorial_production
  host: localhost
